---
- name: Check if NvChad is installed
  stat:
    path: "{{ home_dir }}/.config/nvim"
  register: nvim_config
  tags: ["editors", "neovim"]

- name: Install NvChad
  git:
    repo: https://github.com/NvChad/starter
    dest: "{{ home_dir }}/.config/nvim"
    clone: yes
  when: install_nvchad and not nvim_config.stat.exists
  tags: ["editors", "neovim"]
  
- name: Report NvChad installation skipped
  debug:
    msg: "Skipping NvChad installation (either already installed or disabled in configuration)"
  when: not install_nvchad or nvim_config.stat.exists
  tags: ["editors", "neovim"]