---
- name: Get fish shell path
  command: which fish
  register: fish_path
  changed_when: false
  ignore_errors: true
  tags: ["shell", "fish"]

- name: Set up Fish shell
  block:
    - name: Add fish to /etc/shells
      become: true
      lineinfile:
        dest: /etc/shells
        line: "{{ fish_path.stdout }}"
        state: present
      tags: ["shell", "fish"]

    - name: Set fish as default shell
      become: true
      user:
        name: "{{ user }}"
        shell: "{{ fish_path.stdout }}"
      tags: ["shell", "fish"]

    - name: Create Fish config directories
      file:
        path: "{{ home_dir }}/.config/fish/conf.d"
        state: directory
        mode: '0755'
      tags: ["shell", "fish"]

    - name: Create Nix config for Fish
      copy:
        dest: "{{ home_dir }}/.config/fish/conf.d/nix.fish"
        content: |
          if test -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish
            source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish
          end
        mode: '0644'
      tags: ["shell", "fish", "nix"]

    - name: Install Fisher (Fish plugin manager)
      shell: |
        fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
      args:
        creates: "{{ home_dir }}/.config/fish/functions/fisher.fish"
      tags: ["shell", "fish"]

    - name: Install Fish plugins
      shell: |
        fish -c "fisher install {{ item }}"
      loop: "{{ fish_plugins }}"
      tags: ["shell", "fish"]

    - name: Install Starship prompt
      shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir {{ home_dir }}/.local/bin/
      args:
        creates: "{{ home_dir }}/.local/bin/starship"
      tags: ["shell", "starship"]
      notify: Configure Starship prompt

  when: default_shell == "fish" and fish_path.rc == 0
  tags: ["shell", "fish"]