---
- name: Check if running on Ubuntu/Debian
  debug:
    msg: "This playbook is optimized for Ubuntu/Debian. Some tasks may fail on other distributions."
  when: ansible_distribution != "Ubuntu" and ansible_distribution != "Debian"
  tags: ["common"]

- name: Install Ubuntu/Debian specific packages
  become: true
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags: ["common", "packages"]

- name: Ensure unzip is installed
  become: true
  apt:
    name: unzip
    state: present
    update_cache: no
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  tags: ["common", "packages", "fonts"]