---
- name: Get public key content
  command: "cat {{ effective_home_dir }}/.ssh/id_{{ ssh_key_type }}.pub"
  register: ssh_public_key
  changed_when: false
  tags: ["github", "ssh"]
  
- name: Create unique key title
  set_fact:
    key_title: "{{ ansible_hostname }}-{{ ansible_date_time.date }}"
  tags: ["github", "ssh"]
  
- name: Upload key to GitHub
  uri:
    url: https://api.github.com/user/keys
    method: POST
    body:
      title: "{{ key_title }}"
      key: "{{ ssh_public_key.stdout }}"
    body_format: json
    headers:
      Authorization: "token {{ github.access_token }}"
      Accept: "application/vnd.github+json"
    status_code: [201, 422]  # 422 means key already exists
  register: github_key_upload
  no_log: true
  tags: ["github", "ssh"]
  
- name: Test GitHub SSH connection
  shell: ssh -T -o StrictHostKeyChecking=no git@github.com || true
  args:
    executable: /bin/bash
  register: github_ssh_test
  changed_when: false
  tags: ["github", "ssh"]
  
- name: Display GitHub SSH test results
  debug:
    msg: "{{ github_ssh_test.stdout_lines }}"
  tags: ["github", "ssh"]