---
- name: Include SSH key generation tasks
  include_tasks: ssh_keys.yml
  when: ssh.generate_key | default(true) | bool
  tags: ["ssh", "security"]

- name: Include GitHub SSH key upload tasks
  include_tasks: github_ssh.yml
  when: 
    - github.upload_key | bool
    - github.access_token | length > 0
    - github.username | length > 0
  tags: ["github", "ssh"]