---
# Linux Development Environment Setup Playbook
# This is now a wrapper that runs both phases of the setup
#
# For a smoother experience, run the phases separately:
#   1. ansible-playbook -i inventory.ini phase1-base.yml --ask-become-pass
#   2. (exit and restart terminal)
#   3. ansible-playbook -i inventory.ini phase2-tools.yml --ask-become-pass
#
# Usage with encrypted private config:
#   ansible-playbook -i inventory.ini dev-setup.yml -e "@public-config.yml" -e "@private-config.yml" --ask-vault-pass

- name: Import Phase 1 - Base Environment
  import_playbook: phase1-base.yml

- name: Import Phase 2 - Tools and Configuration
  import_playbook: phase2-tools.yml