---
# Phase 1: Base Environment Setup
# This playbook sets up the fundamental environment (package managers, shell)

- name: Setup Linux Development Environment - Phase 1
  hosts: localhost
  become: false  # Escalate privileges only when needed
  gather_facts: true

  pre_tasks:
    - name: Load configuration files
      include_tasks: tasks/load_config.yml
      tags: ["always"]

    - name: Set default user after configuration loading
      set_fact:
        user: "{{ user | default(ansible_user_id, true) }}"
        home_dir: "{{ home_dir | default(ansible_env.HOME, true) }}"
      tags: ["always"]

  vars:
    # Only environment variables that need to be determined at runtime
    user: "{{ lookup('env', 'USER') | default(ansible_user_id, true) }}"
    home_dir: "{{ lookup('env', 'HOME') | default(ansible_env.HOME, true) }}"
    # All other variables should be defined in configuration files or role defaults

  roles:
    # First, install essential packages
    - common
    
    # Then, set up package managers
    - nix
    - homebrew
    
    # Then set up the shell (which depends on some packages being installed)
    - { role: shell, when: default_shell is defined and default_shell != "" }

  post_tasks:
    - name: Display next steps
      debug:
        msg: |
          Phase 1 complete! Base environment has been set up.
          
          IMPORTANT: Environment changes have been made that require a new shell session.
          
          NEXT STEPS:
          1. Exit your terminal completely
          2. Open a new terminal
          3. Run the Phase 2 playbook:
             ansible-playbook -i inventory.ini phase2-tools.yml --ask-become-pass
      tags: ["always"]