---
- name: Check if Nix is installed
  stat:
    path: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  register: nix_installed
  changed_when: false
  tags: ["nix"]

- name: Install Nix package manager
  block:
    - name: Download Nix installer
      get_url:
        url: https://install.determinate.systems/nix
        dest: /tmp/nix-installer.sh
        mode: '0755'
      
    - name: Run Nix installer
      shell: |
        /tmp/nix-installer.sh install --no-confirm
      args:
        creates: /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      
    - name: Clean up Nix installer
      file:
        path: /tmp/nix-installer.sh
        state: absent
  when: not nix_installed.stat.exists
  tags: ["nix", "packages"]

- name: Source Nix environment (temporary for this playbook)
  shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    echo "$PATH"
  register: nix_path
  changed_when: false
  when: not nix_installed.stat.exists
  tags: ["nix"]

- name: Install packages with Nix
  shell: |
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    nix profile install {{ nix_packages | join(' ') }}
  args:
    executable: /bin/bash
  register: nix_install
  changed_when: "'error' not in nix_install.stderr"
  when: nix_packages | length > 0
  tags: ["nix", "packages"]